# Generated by Django 2.2.14 on 2024-01-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240111_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='core.Categories'),
        ),
    ]
